theme: jekyll-theme-cayman
title: Manual tagging of Illegal Wildlife Trade (IWT)
author: Prakirth, Alastair Jamieson
email: prakirth112@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
  JSON files extracted by the python algorithm will be uploaded for manually identifying the images for IWT based on the comments, hashtags & image content.
  
# social links
twitter_username: prakgov # DO NOT include the @ character, or else the build will fail!
github_username:  prak112 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
